### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by sonnyk22** [BillyFnh/Node-Facial-Recognition#2]
I enjoyed reading your great article at this link: [https://medium.com/swlh/how-to-setup-mongodb-replica-set-on-kubernetes-in-minutes-5c1e7fd5b5f3](url).

Is it possible for you to push its related AKS/MongoDB/Yamls repo back up to the Github again?

Thank you

**Comment by BillyFnh** [comment]
Hi @sonnyk22,

Apologies for the late response, this project should have what you're looking for:

[MongoDB ReplicaSet On K8s](https://github.com/BillyFnh/MongoDB-ReplicaSet-on-K8s)

If you'd like any further clarification on this topic, feel free to open new issues on that GitHub project!
